# MUSHCODE MCP Server - Network Mode Docker Compose
version: '3.8'

services:
  mushcode-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: mushcode-mcp-server:latest
    container_name: mushcode-mcp-server-network
    restart: unless-stopped
    
    # Environment variables for network mode
    environment:
      - NODE_ENV=production
      - MUSHCODE_LOG_LEVEL=info
      - MUSHCODE_CACHE_SIZE=1000
      - MUSHCODE_CACHE_TTL=300000
      - NETWORK_PORT=3001
      - ALLOWED_ORIGINS=*
      # Security options (uncomment and configure for production)
      # - API_KEY=your-secret-api-key-here
      # - ENABLE_RATE_LIMITING=true
      # - RATE_LIMIT_WINDOW_MS=60000
      # - RATE_LIMIT_MAX_REQUESTS=100
    
    # Port mapping for network access
    ports:
      - "3001:3001"
    
    # Volume mounts for persistent data
    volumes:
      - mushcode-logs:/app/logs
      - mushcode-cache:/app/cache
      - ./mushcode-mcp.config.json:/app/mushcode-mcp.config.json:ro
    
    # Override the default command to use network server
    command: ["node", "dist/server/network-server.js"]
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Health check for network server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for specific writable directories)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Named volumes for persistent data
volumes:
  mushcode-logs:
    driver: local
  mushcode-cache:
    driver: local

# Network configuration
networks:
  default:
    driver: bridge