# MUSHCODE MCP Server - Docker Compose for Production
version: '3.8'

services:
  mushcode-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: mushcode-mcp-server:latest
    container_name: mushcode-mcp-server
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - MUSHCODE_LOG_LEVEL=info
      - MUSHCODE_CACHE_SIZE=1000
      - MUSHCODE_CACHE_TTL=300000
      - PORT=3000
    
    # Port mapping (optional - MCP typically uses stdio)
    ports:
      - "3000:3000"
    
    # Volume mounts for persistent data
    volumes:
      - mushcode-logs:/app/logs
      - mushcode-cache:/app/cache
      - ./mushcode-mcp.config.json:/app/mushcode-mcp.config.json:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "import('./dist/server/index.js').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for specific writable directories)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Named volumes for persistent data
volumes:
  mushcode-logs:
    driver: local
  mushcode-cache:
    driver: local

# Network configuration
networks:
  default:
    driver: bridge